Traceback (most recent call last):
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/bcd/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize=(8,8))
ds.plot.countplot(y='calc type', ax=ax, title ="Distribution of Calcification Type")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m8[39m,[38;5;241m8[39m))
[0;32m----> 2[0m [43mds[49m[38;5;241;43m.[39;49m[43mplot[49m[38;5;241;43m.[39;49m[43mcountplot[49m[43m([49m[43my[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mcalc type[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m,[49m[43m [49m[43mtitle[49m[43m [49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mDistribution of Calcification Type[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/bcd/lib/python3.10/site-packages/studioai/visual/seaborn.py:378[0m, in [0;36mVisualizer.countplot[0;34m(self, data, x, y, hue, orient, title, ax, *args, **kwargs)[0m
[1;32m    375[0m [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    376[0m     fig, ax [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_canvas[38;5;241m.[39mget_figaxes()
[0;32m--> 378[0m [43msns[49m[38;5;241;43m.[39;49m[43mcountplot[49m[43m([49m
[1;32m    379[0m [43m    [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdata[49m[43m,[49m
[1;32m    380[0m [43m    [49m[43mx[49m[38;5;241;43m=[39;49m[43mx[49m[43m,[49m
[1;32m    381[0m [43m    [49m[43my[49m[38;5;241;43m=[39;49m[43my[49m[43m,[49m
[1;32m    382[0m [43m    [49m[43mhue[49m[38;5;241;43m=[39;49m[43mhue[49m[43m,[49m
[1;32m    383[0m [43m    [49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m,[49m
[1;32m    384[0m [43m    [49m[43mpalette[49m[38;5;241;43m=[39;49m[43mpalette[49m[43m,[49m
[1;32m    385[0m [43m    [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m
[1;32m    386[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    387[0m [43m[49m[43m)[49m
[1;32m    388[0m [38;5;28;01mif[39;00m orient [38;5;241m==[39m [38;5;124m"[39m[38;5;124mv[39m[38;5;124m"[39m:
[1;32m    389[0m     [38;5;28;01mfor[39;00m p [38;5;129;01min[39;00m ax[38;5;241m.[39mpatches:

File [0;32m~/anaconda3/envs/bcd/lib/python3.10/site-packages/seaborn/categorical.py:2943[0m, in [0;36mcountplot[0;34m(data, x, y, hue, order, hue_order, orient, color, palette, saturation, width, dodge, ax, **kwargs)[0m
[1;32m   2940[0m [38;5;28;01melif[39;00m x [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m y [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   2941[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mCannot pass values for both `x` and `y`[39m[38;5;124m"[39m)
[0;32m-> 2943[0m plotter [38;5;241m=[39m [43m_CountPlotter[49m[43m([49m
[1;32m   2944[0m [43m    [49m[43mx[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43mhue[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43morder[49m[43m,[49m[43m [49m[43mhue_order[49m[43m,[49m
[1;32m   2945[0m [43m    [49m[43mestimator[49m[43m,[49m[43m [49m[43merrorbar[49m[43m,[49m[43m [49m[43mn_boot[49m[43m,[49m[43m [49m[43munits[49m[43m,[49m[43m [49m[43mseed[49m[43m,[49m
[1;32m   2946[0m [43m    [49m[43morient[49m[43m,[49m[43m [49m[43mcolor[49m[43m,[49m[43m [49m[43mpalette[49m[43m,[49m[43m [49m[43msaturation[49m[43m,[49m
[1;32m   2947[0m [43m    [49m[43mwidth[49m[43m,[49m[43m [49m[43merrcolor[49m[43m,[49m[43m [49m[43merrwidth[49m[43m,[49m[43m [49m[43mcapsize[49m[43m,[49m[43m [49m[43mdodge[49m
[1;32m   2948[0m [43m[49m[43m)[49m
[1;32m   2950[0m plotter[38;5;241m.[39mvalue_label [38;5;241m=[39m [38;5;124m"[39m[38;5;124mcount[39m[38;5;124m"[39m
[1;32m   2952[0m [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/envs/bcd/lib/python3.10/site-packages/seaborn/categorical.py:1530[0m, in [0;36m_BarPlotter.__init__[0;34m(self, x, y, hue, data, order, hue_order, estimator, errorbar, n_boot, units, seed, orient, color, palette, saturation, width, errcolor, errwidth, capsize, dodge)[0m
[1;32m   1525[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, x, y, hue, data, order, hue_order,
[1;32m   1526[0m              estimator, errorbar, n_boot, units, seed,
[1;32m   1527[0m              orient, color, palette, saturation, width,
[1;32m   1528[0m              errcolor, errwidth, capsize, dodge):
[1;32m   1529[0m [38;5;250m    [39m[38;5;124;03m"""Initialize the plotter."""[39;00m
[0;32m-> 1530[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mestablish_variables[49m[43m([49m[43mx[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43mhue[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43morient[49m[43m,[49m
[1;32m   1531[0m [43m                             [49m[43morder[49m[43m,[49m[43m [49m[43mhue_order[49m[43m,[49m[43m [49m[43munits[49m[43m)[49m
[1;32m   1532[0m     [38;5;28mself[39m[38;5;241m.[39mestablish_colors(color, palette, saturation)
[1;32m   1533[0m     [38;5;28mself[39m[38;5;241m.[39mestimate_statistic(estimator, errorbar, n_boot, seed)

File [0;32m~/anaconda3/envs/bcd/lib/python3.10/site-packages/seaborn/categorical.py:541[0m, in [0;36m_CategoricalPlotter.establish_variables[0;34m(self, x, y, hue, data, orient, order, hue_order, units)[0m
[1;32m    539[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(var, [38;5;28mstr[39m):
[1;32m    540[0m         err [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCould not interpret input [39m[38;5;124m'[39m[38;5;132;01m{[39;00mvar[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m
[0;32m--> 541[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(err)
[1;32m    543[0m [38;5;66;03m# Figure out the plotting orientation[39;00m
[1;32m    544[0m orient [38;5;241m=[39m infer_orient(
[1;32m    545[0m     x, y, orient, require_numeric[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mrequire_numeric
[1;32m    546[0m )

[0;31mValueError[0m: Could not interpret input 'calc type'

